spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: first
            predicates:
              - Path=/gw/call
            filters:
                - StripPrefix=1
            uri: http://localhost:3000/call